name: サウナ施設の新規登録
description: 新しいサウナ・温泉施設をマップに追加します(自動でマップに反映されます)
title: "[サウナ登録] "
labels: ["sauna-entry"]
body:
  - type: input
    id: facility_name
    attributes:
      label: 施設名
      placeholder: 例) 休日ビルヂング
    validations:
      required: true
  - type: input
    id: pref
    attributes:
      label: 都道府県
      placeholder: 例) 北海道
    validations:
      required: true
  - type: input
    id: region
    attributes:
      label: 地域(市区町村や俗称)
      placeholder: 例) 定山渓
  - type: input
    id: url
    attributes:
      label: 施設URL
      placeholder: https://
  - type: textarea
    id: good
    attributes:
      label: 良かった点
      description: 1行に1つずつ書いてください
  - type: textarea
    id: bad
    attributes:
      label: 気になった点
      description: 1行に1つずつ書いてください
  - type: dropdown
    id: rating
    attributes:
      label: またイキタイ度
      options: ["5", "4", "3", "2", "1"]
    validations:
      required: true
  - type: input
    id: poster
    attributes:
      label: お名前
      description: マップ上では自動的に「部員A」のように匿名化されます
